"""initial schema

Revision ID: 58838d4ef4cf
Revises: 
Create Date: 2026-09-19 15:07:26.344784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58838d4ef4cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS partners")
    op.create_table('airlines',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('airports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('iata', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('is_hub', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata')
    )
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('routing_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bag_tags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('saga_id', sa.String(length=64), nullable=False),
    sa.Column('pnr', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='partners'
    )
    op.create_table('idempotency',
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key'),
    schema='partners'
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('saga_id', sa.String(length=64), nullable=False),
    sa.Column('pnr', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='partners'
    )
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('minio_key', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('airline_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('flight_no', sa.String(length=16), nullable=False),
    sa.Column('tail_number', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dest', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dep_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arr_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sched_dep_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sched_arr_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('SCHEDULED', 'DELAYED', 'CANCELLED')", name='ck_flights_status'),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.ForeignKeyConstraint(['dest'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['origin'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('airline_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('is_unaccompanied_minor', sa.Boolean(), nullable=False),
    sa.Column('bags', sa.Integer(), nullable=False),
    sa.CheckConstraint("tier IN ('NONE', 'SILVER', 'GOLD')", name='ck_passengers_tier'),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scenario_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('CREATED', 'RUNNING', 'FINISHED')", name='ck_runs_status'),
    sa.CheckConstraint("strategy IN ('greedy', 'cpsat')", name='ck_runs_strategy'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('passenger_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pnr', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'DISRUPTED', 'REBOOKED', 'UNRECOVERED')", name='ck_bookings_status'),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnr')
    )
    op.create_table('disruption_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('cause', sa.String(length=16), nullable=False),
    sa.Column('target_flight_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_airport_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cause IN ('WEATHER', 'AOG', 'CREW', 'CASCADE', 'ATC')", name='ck_disruption_events_cause'),
    sa.CheckConstraint("type IN ('CANCELLATION', 'DELAY')", name='ck_disruption_events_type'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['target_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['target_flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_inventory',
    sa.Column('flight_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cabin', sa.String(length=16), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('sold_other', sa.Integer(), nullable=False),
    sa.CheckConstraint('available <= capacity', name='ck_seat_inventory_available_le_capacity'),
    sa.CheckConstraint('available >= 0', name='ck_seat_inventory_available_nonneg'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('flight_id', 'cabin')
    )
    op.create_table('booking_segments',
    sa.Column('booking_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cabin', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('booking_id', 'seq')
    )
    op.create_table('sagas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('booking_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('current_step', sa.String(length=24), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('PLANNED', 'HOLDING', 'TICKETING', 'BAGGAGE', 'NOTIFYING', 'COMPLETED', 'COMPENSATING', 'COMPENSATED', 'FAILED_NO_CAPACITY', 'NEEDS_MANUAL')", name='ck_sagas_state'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'booking_id', name='uq_sagas_run_booking')
    )
    op.create_table('dead_letters',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('saga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('step', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_messages',
    sa.Column('saga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('step', sa.String(length=24), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('saga_id', 'step')
    )
    op.create_table('saga_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('saga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saga_id', 'seq', name='uq_saga_events_saga_seq')
    )
    op.create_table('seat_holds',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('saga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('flight_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cabin', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('HELD', 'CONFIRMED', 'RELEASED')", name='ck_seat_holds_status'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['saga_id'], ['sagas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saga_id', 'flight_id', 'cabin', name='uq_seat_holds_saga_flight_cabin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_holds')
    op.drop_table('saga_events')
    op.drop_table('processed_messages')
    op.drop_table('dead_letters')
    op.drop_table('sagas')
    op.drop_table('booking_segments')
    op.drop_table('seat_inventory')
    op.drop_table('disruption_events')
    op.drop_table('bookings')
    op.drop_table('runs')
    op.drop_table('passengers')
    op.drop_table('flights')
    op.drop_table('scenarios')
    op.drop_table('tickets', schema='partners')
    op.drop_table('idempotency', schema='partners')
    op.drop_table('bag_tags', schema='partners')
    op.drop_table('outbox')
    op.drop_table('airports')
    op.drop_table('airlines')
    op.execute("DROP SCHEMA IF EXISTS partners CASCADE")
    # ### end Alembic commands ###
