"""String constants for status/state/type columns.

Plain strings + CHECK constraints are used instead of native Postgres ENUMs
so that adding a new value later is a cheap constraint change, not a type
migration.
"""

# flights.status
FLIGHT_SCHEDULED = "SCHEDULED"
FLIGHT_DELAYED = "DELAYED"
FLIGHT_CANCELLED = "CANCELLED"
FLIGHT_STATUSES = (FLIGHT_SCHEDULED, FLIGHT_DELAYED, FLIGHT_CANCELLED)

# passengers.tier
TIER_NONE = "NONE"
TIER_SILVER = "SILVER"
TIER_GOLD = "GOLD"
TIERS = (TIER_NONE, TIER_SILVER, TIER_GOLD)

# bookings.status
BOOKING_ACTIVE = "ACTIVE"
BOOKING_DISRUPTED = "DISRUPTED"
BOOKING_REBOOKED = "REBOOKED"
BOOKING_UNRECOVERED = "UNRECOVERED"
BOOKING_STATUSES = (BOOKING_ACTIVE, BOOKING_DISRUPTED, BOOKING_REBOOKED, BOOKING_UNRECOVERED)

# disruption_events.type
EVENT_CANCELLATION = "CANCELLATION"
EVENT_DELAY = "DELAY"
EVENT_TYPES = (EVENT_CANCELLATION, EVENT_DELAY)

# disruption_events.cause
CAUSE_WEATHER = "WEATHER"
CAUSE_AOG = "AOG"
CAUSE_CREW = "CREW"
CAUSE_CASCADE = "CASCADE"
CAUSE_ATC = "ATC"
CAUSES = (CAUSE_WEATHER, CAUSE_AOG, CAUSE_CREW, CAUSE_CASCADE, CAUSE_ATC)

# runs.strategy
STRATEGY_GREEDY = "greedy"
STRATEGY_CPSAT = "cpsat"
STRATEGIES = (STRATEGY_GREEDY, STRATEGY_CPSAT)

# runs.status
RUN_CREATED = "CREATED"
RUN_RUNNING = "RUNNING"
RUN_FINISHED = "FINISHED"
RUN_STATUSES = (RUN_CREATED, RUN_RUNNING, RUN_FINISHED)

# sagas.state
SAGA_PLANNED = "PLANNED"
SAGA_HOLDING = "HOLDING"
SAGA_TICKETING = "TICKETING"
SAGA_BAGGAGE = "BAGGAGE"
SAGA_NOTIFYING = "NOTIFYING"
SAGA_COMPLETED = "COMPLETED"
SAGA_COMPENSATING = "COMPENSATING"
SAGA_COMPENSATED = "COMPENSATED"
SAGA_FAILED_NO_CAPACITY = "FAILED_NO_CAPACITY"
SAGA_NEEDS_MANUAL = "NEEDS_MANUAL"
SAGA_STATES = (
    SAGA_PLANNED,
    SAGA_HOLDING,
    SAGA_TICKETING,
    SAGA_BAGGAGE,
    SAGA_NOTIFYING,
    SAGA_COMPLETED,
    SAGA_COMPENSATING,
    SAGA_COMPENSATED,
    SAGA_FAILED_NO_CAPACITY,
    SAGA_NEEDS_MANUAL,
)
SAGA_TERMINAL_STATES = (
    SAGA_COMPLETED,
    SAGA_COMPENSATED,
    SAGA_FAILED_NO_CAPACITY,
    SAGA_NEEDS_MANUAL,
)

# saga steps (also used as routing keys under saga.steps.<step>)
STEP_HOLD_SEATS = "HOLD_SEATS"
STEP_ISSUE_TICKET = "ISSUE_TICKET"
STEP_RETAG_BAGS = "RETAG_BAGS"
STEP_NOTIFY = "NOTIFY"
STEP_RELEASE_SEATS = "RELEASE_SEATS"
STEP_VOID_TICKET = "VOID_TICKET"
STEP_UNDO_RETAG = "UNDO_RETAG"
FORWARD_STEPS = (STEP_HOLD_SEATS, STEP_ISSUE_TICKET, STEP_RETAG_BAGS, STEP_NOTIFY)
COMPENSATION_STEPS = (STEP_UNDO_RETAG, STEP_VOID_TICKET, STEP_RELEASE_SEATS)

# seat_holds.status
HOLD_HELD = "HELD"
HOLD_CONFIRMED = "CONFIRMED"
HOLD_RELEASED = "RELEASED"
HOLD_STATUSES = (HOLD_HELD, HOLD_CONFIRMED, HOLD_RELEASED)
